apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkroutes.gitops.netbird.io
spec:
  group: gitops.netbird.io
  names:
    kind: NetworkRoute
    listKind: NetworkRouteList
    plural: networkroutes
    singular: networkroute
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.status
          name: Ready
          type: string
        - jsonPath: .status.resourceId
          name: RouteID
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - network
                - peerId
                - groups
                - network_id
              properties:
                network:
                  type: string
                  pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$'
                peerId:
                  type: string
                groups:
                  type: array
                  items:
                    type: string
                network_id:
                  type: string
                description:
                  type: string
                enabled:
                  type: boolean
                  default: true
                masquerade:
                  type: boolean
                  default: false
                metric:
                  type: integer
                  minimum: 0
                  default: 9999
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                lastSync:
                  type: string
                  format: date-time
                resourceId:
                  type: string
                status:
                  type: string
                  enum: ['True', 'False', 'Unknown']
                reason:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                      - lastTransitionTime
                      - reason
                      - message
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ['True', 'False', 'Unknown']
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.gitops.netbird.io
spec:
  group: gitops.netbird.io
  names:
    kind: Group
    listKind: GroupList
    plural: groups
    singular: group
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.status
          name: Ready
          type: string
        - jsonPath: .status.resourceId
          name: GroupID
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                description:
                  type: string
                peers:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                lastSync:
                  type: string
                  format: date-time
                resourceId:
                  type: string
                status:
                  type: string
                  enum: ['True', 'False', 'Unknown']
                reason:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                      - lastTransitionTime
                      - reason
                      - message
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ['True', 'False', 'Unknown']
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}