---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netbird-operator
  namespace: netbird-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netbird-operator
rules:
- apiGroups: ["networking.netbird.io"]
  resources: ["netbirdroutes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.netbird.io"]
  resources: ["netbirdroutes/status"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netbird-operator
subjects:
- kind: ServiceAccount
  name: netbird-operator
  namespace: netbird-system
roleRef:
  kind: ClusterRole
  name: netbird-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-operator
  namespace: netbird-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-operator
  template:
    metadata:
      labels:
        app: netbird-operator
    spec:
      serviceAccountName: netbird-operator
      containers:
      - name: operator
        image: 1doce8/netbird-operator:latest  # You'll need to build and push this image
        env:
        - name: NETBIRD_URL
          value: "https://vpn.infra.enterprise.onerpc.com/api"
        - name: NETBIRD_API_KEY
          value: "nbp_UBGIDopCbTyBCbmqUxsD5PB9pX0Xsy2B10fe"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
