---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: netbirdroutes.networking.netbird.io
spec:
  group: networking.netbird.io
  names:
    kind: NetbirdRoute
    plural: netbirdroutes
    singular: netbirdroute
    shortNames:
      - nbr
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - network
                - peerId
                - groups
                - network_id
              properties:
                network:
                  type: string
                peerId:
                  type: string
                groups:
                  type: array
                  items:
                    type: string
                network_id:
                  type: string
                description:
                  type: string
                enabled:
                  type: boolean
                masquerade:
                  type: boolean
                metric:
                  type: integer
            status:
              type: object
              properties:
                create_fn:  # Add this to match kopf's status structure
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                update_fn:  # Add this to match kopf's status structure
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                delete_fn:  # Add this to match kopf's status structure
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                routeId:
                  type: string
                lastSync:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}