---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkroutes.gitops.netbird.io
spec:
  group: gitops.netbird.io
  names:
    kind: NetworkRoute
    plural: networkroutes
    singular: networkroute
    shortNames:
      - nbr
  scope: Namespaced  # Changed from Cluster to Namespaced for better isolation
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Reason
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].reason
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - network
                - peerId
                - groups
                - network_id
              properties:
                network:
                  type: string
                  description: "Network CIDR"
                peerId:
                  type: string
                  description: "Netbird Peer ID"
                groups:
                  type: array
                  description: "List of group IDs"
                  items:
                    type: string
                network_id:
                  type: string
                  description: "Network identifier"
                description:
                  type: string
                  description: "Route description"
                enabled:
                  type: boolean
                  description: "Route enabled status"
                  default: true
                masquerade:
                  type: boolean
                  description: "Masquerade status"
                  default: false
                metric:
                  type: integer
                  description: "Route metric"
                  default: 9999
            status:
              type: object
              properties:
                resourceID:
                  type: string
                  description: "Netbird route ID"
                lastSync:
                  type: string
                  description: "Last synchronization timestamp"
                create_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                update_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                delete_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.gitops.netbird.io
spec:
  group: gitops.netbird.io
  names:
    kind: Groups
    # listKind: NetbirdGroupList
    plural: groups
    singular: group
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["name"]
              properties:
                name:
                  type: string
                  description: "Name of the group"
                description:
                  type: string
                  description: "Description of the group"
            status:
              type: object
              properties:
                resourceID:
                  type: string
                  description: "Netbird group ID"
                lastSync:
                  type: string
                  description: "Last synchronization timestamp"
                create_group_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                # update_fn:
                #   type: object
                #   x-kubernetes-preserve-unknown-fields: true
                delete_group_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Group ID
          type: string
          jsonPath: .status.resourceID
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}