---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netbird-operator
  namespace: netbird-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netbird-operator-admin
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netbird-operator-admin
subjects:
  - kind: ServiceAccount
    name: netbird-operator
    namespace: netbird-system
roleRef:
  kind: ClusterRole
  name: netbird-operator-admin
  apiGroup: rbac.authorization.k8s.io
